---
openapi: 3.0.3
info:
  title: Draivn OneApi
  description: Draivn OneApi
  contact:
    name: Draivn OneApi
    url: https://draivn.com
    email: techsupport@draivn.com
  version: 2.1.0

servers:
  - url: https://draivn.com
    description: Draivn OneApi

paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
